library:
  source-dirs: src
tests:
  wai-test-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wai-test
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - http-types
  - warp
  - wai
  - base >= 4.7 && < 5
  - text
  - bytestring
name: wai-test
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/wai-test
license: BSD3
executables:
  wai-test-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wai-test
description: Please see the README on GitHub at <https://github.com/githubuser/wai-test#readme>
