library:
  source-dirs: src
tests:
  wai-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wai
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - wai
  - base >= 4.7 && < 5
name: wai
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/wai
license: BSD3
executables:
  wai-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wai
description: Please see the README on GitHub at <https://github.com/githubuser/wai#readme>
